
export interface ExtracurricularActivity {
  name: string;
  type: string;
  category: string;
  province: string;
  startDate?: string;
  endDate?: string;
  applicationDeadline?: string;
  ageRange: string;
  skillsRequired?: string;
  skillsGained: string;
  website: string;
  competitive: boolean;
  annual: boolean;
  format: string;
  image: string;
  hint: string;
}

export const activities: ExtracurricularActivity[] = [
  {
    "name": "SHAD Canada",
    "type": "Program",
    "category": "STEM",
    "province": "National",
    "startDate": "July 5, 2025",
    "endDate": "July 31, 2025",
    "applicationDeadline": "December 1, 2024",
    "ageRange": "16-18",
    "skillsRequired": "Academic Excellence, Leadership Potential",
    "skillsGained": "STEM Skills, Leadership, Innovation, Entrepreneurship",
    "website": "https://www.shad.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person/Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "innovation lab"
  },
  {
    "name": "Canadian Mathematical Olympiad (CMO)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "March 2025",
    "endDate": "March 2025",
    "applicationDeadline": "Based on COMC performance",
    "ageRange": "14-18",
    "skillsRequired": "Advanced Mathematics, Problem Solving",
    "skillsGained": "Mathematical Reasoning, Critical Thinking",
    "website": "https://cms.math.ca/competitions/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "math equation"
  },
  {
    "name": "Canadian Open Mathematics Challenge (COMC)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "October 30, 2024",
    "endDate": "October 30, 2024",
    "applicationDeadline": "October 2024",
    "ageRange": "14-18",
    "skillsRequired": "Advanced Mathematics",
    "skillsGained": "Problem Solving, Mathematical Analysis",
    "website": "https://cms.math.ca/competitions/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "mathematics exam"
  },
  {
    "name": "Euclid Mathematics Contest",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "April 2, 2025",
    "endDate": "April 2, 2025",
    "applicationDeadline": "March 2025",
    "ageRange": "17-18",
    "skillsRequired": "Grade 12 Mathematics",
    "skillsGained": "Advanced Problem Solving, University Preparation",
    "website": "https://cemc.uwaterloo.ca/contests",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "geometry problem"
  },
  {
    "name": "Pascal, Cayley, Fermat Contests",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "February 26, 2025",
    "endDate": "February 26, 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "14-16",
    "skillsRequired": "Mathematics (Grades 9-11)",
    "skillsGained": "Mathematical Problem Solving",
    "website": "https://cemc.uwaterloo.ca/contests",
    "competitive": true,
    "annual": true,
    "format": "In-person/Online",
    "image": "https://placehold.co/600x400.png",
    "hint": "math competition"
  },
  {
    "name": "Canadian Physics Olympiad (CAP)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "April 2025",
    "endDate": "April 2025",
    "applicationDeadline": "March 2025",
    "ageRange": "16-18",
    "skillsRequired": "Advanced Physics",
    "skillsGained": "Physics Problem Solving, Scientific Reasoning",
    "website": "https://cap.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "physics experiment"
  },
  {
    "name": "Canadian Chemistry Competition (CCC)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "April 23, 2025",
    "endDate": "April 23, 2025",
    "applicationDeadline": "April 2025",
    "ageRange": "16-18",
    "skillsRequired": "Advanced Chemistry",
    "skillsGained": "Chemical Analysis, Laboratory Skills",
    "website": "https://www.cheminst.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "chemistry lab"
  },
  {
    "name": "Canadian Biology Olympiad (CBO)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "April 10, 2025",
    "endDate": "April 10, 2025",
    "applicationDeadline": "March 2025",
    "ageRange": "16-18",
    "skillsRequired": "Advanced Biology",
    "skillsGained": "Biological Analysis, Research Skills",
    "website": "https://cbo-ibo.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "biology microscope"
  },
  {
    "name": "Canadian Computing Competition (CCC)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "February 2025",
    "endDate": "February 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "14-18",
    "skillsRequired": "Programming, Problem Solving",
    "skillsGained": "Algorithmic Thinking, Coding Skills",
    "website": "https://cemc.uwaterloo.ca/contests/ccc",
    "competitive": true,
    "annual": true,
    "format": "Online",
    "image": "https://placehold.co/600x400.png",
    "hint": "coding competition"
  },
  {
    "name": "Canada-Wide Science Fair (CWSF)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "May 2025",
    "endDate": "May 2025",
    "applicationDeadline": "Qualify through regional fairs",
    "ageRange": "13-18",
    "skillsRequired": "Scientific Research, Presentation",
    "skillsGained": "Research Methodology, Scientific Communication",
    "website": "https://cwsf-espc.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "science fair"
  },
  {
    "name": "Sanofi Biogenius Canada Competition",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "September 2024",
    "endDate": "May 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "16-18",
    "skillsRequired": "Life Sciences Research",
    "skillsGained": "Biotechnology, Research Skills, Presentation",
    "website": "https://biogenius.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "biotechnology research"
  },
  {
    "name": "Canadian High Schools Model United Nations (CAHSMUN)",
    "type": "Conference",
    "category": "Leadership",
    "province": "British Columbia",
    "startDate": "February 2025",
    "endDate": "February 2025",
    "applicationDeadline": "January 2025",
    "ageRange": "14-18",
    "skillsRequired": "Public Speaking, Research, Diplomacy",
    "skillsGained": "Debate, International Relations, Leadership",
    "website": "https://cahsmun.org/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "model un"
  },
  {
    "name": "DECA Canada Provincial Competition",
    "type": "Competition",
    "category": "Business",
    "province": "Ontario",
    "startDate": "February 6, 2026",
    "endDate": "February 7, 2026",
    "applicationDeadline": "November 2025",
    "ageRange": "14-18",
    "skillsRequired": "Business Knowledge, Presentation",
    "skillsGained": "Marketing, Finance, Entrepreneurship, Public Speaking",
    "website": "https://deca.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "business competition"
  },
  {
    "name": "FIRST Robotics Competition Canada",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "January 2025",
    "endDate": "April 2025",
    "applicationDeadline": "October 2024",
    "ageRange": "14-18",
    "skillsRequired": "Engineering, Programming, Teamwork",
    "skillsGained": "Robotics, Engineering Design, Project Management",
    "website": "https://firstroboticscanada.org/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "robotics competition"
  },
  {
    "name": "Duke of Edinburgh Award Canada",
    "type": "Award",
    "category": "Leadership",
    "province": "National",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "14-24",
    "skillsRequired": "Commitment, Goal Setting",
    "skillsGained": "Leadership, Community Service, Physical Fitness, Life Skills",
    "website": "https://www.dukeofed.org/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "outdoor adventure"
  },
  {
    "name": "Youth Parliament of Canada",
    "type": "Program",
    "category": "Leadership",
    "province": "National",
    "startDate": "Summer 2025",
    "endDate": "Summer 2025",
    "applicationDeadline": "Spring 2025",
    "ageRange": "16-20",
    "skillsRequired": "Civic Interest, Communication",
    "skillsGained": "Parliamentary Procedure, Leadership, Public Policy",
    "website": "https://civix.ca/youthparliament/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "parliament building"
  },
  {
    "name": "House of Commons Page Program",
    "type": "Program",
    "category": "Leadership",
    "province": "National",
    "startDate": "September 2025",
    "endDate": "June 2026",
    "applicationDeadline": "January 2025",
    "ageRange": "17-20",
    "skillsRequired": "Academic Excellence, Bilingualism",
    "skillsGained": "Parliamentary Knowledge, Leadership, Communication",
    "website": "https://www.ourcommons.ca/about/pageprogram/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "government building"
  },
  {
    "name": "Canada Service Corps",
    "type": "Volunteering",
    "category": "Community Service",
    "province": "National",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "12-30",
    "skillsRequired": "Community Interest",
    "skillsGained": "Leadership, Networking, Essential Skills",
    "website": "https://www.canada.ca/en/services/youth/canada-service-corps.html",
    "competitive": false,
    "annual": true,
    "format": "In-person/Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "community volunteering"
  },
  {
    "name": "Terry Fox Run School Participation",
    "type": "Volunteering",
    "category": "Community Service",
    "province": "National",
    "startDate": "September 2025",
    "endDate": "September 2025",
    "applicationDeadline": "August 2025",
    "ageRange": "5-18",
    "skillsRequired": "None",
    "skillsGained": "Community Engagement, Social Responsibility",
    "website": "https://terryfox.org/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "charity run"
  },
  {
    "name": "MasseyHacks",
    "type": "Hackathon",
    "category": "STEM",
    "province": "Ontario",
    "startDate": "May 2025",
    "endDate": "May 2025",
    "applicationDeadline": "April 2025",
    "ageRange": "13-18",
    "skillsRequired": "Programming Interest",
    "skillsGained": "Coding, Innovation, Teamwork, Product Development",
    "website": "https://masseyhacks.com/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "hackathon event"
  },
  {
    "name": "JAMHacks",
    "type": "Hackathon",
    "category": "STEM",
    "province": "Ontario",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "13-18",
    "skillsRequired": "Programming Interest",
    "skillsGained": "Software Development, Innovation, Collaboration",
    "website": "https://www.jamhacks.ca/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "coding on laptop"
  },
  {
    "name": "Hack The Ridge",
    "type": "Hackathon",
    "category": "STEM",
    "province": "Ontario",
    "startDate": "Various",
    "endDate": "Various",
    "applicationDeadline": "Rolling",
    "ageRange": "14-18",
    "skillsRequired": "Technology Interest",
    "skillsGained": "Problem Solving, Innovation, Technology Skills",
    "website": "https://www.hacktheridge.ca/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "students collaborating"
  },
  {
    "name": "EurekaHACKS",
    "type": "Hackathon",
    "category": "STEM",
    "province": "National",
    "startDate": "Various",
    "endDate": "Various",
    "applicationDeadline": "Rolling",
    "ageRange": "14-18",
    "skillsRequired": "None (Beginner Friendly)",
    "skillsGained": "Coding, Innovation, Technology, Entrepreneurship",
    "website": "https://eurekahacks.ca/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "team brainstorming"
  },
  {
    "name": "CalgaryHacks",
    "type": "Hackathon",
    "category": "STEM",
    "province": "Alberta",
    "startDate": "Various",
    "endDate": "Various",
    "applicationDeadline": "Rolling",
    "ageRange": "16-25",
    "skillsRequired": "Programming Interest",
    "skillsGained": "Software Development, Innovation, Networking",
    "website": "https://calgaryhacks.com/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "city skyline"
  },
  {
    "name": "Futurpreneur Core Startup Program",
    "type": "Program",
    "category": "Business",
    "province": "National",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "18-39",
    "skillsRequired": "Entrepreneurship Interest, Business Idea",
    "skillsGained": "Business Planning, Entrepreneurship, Mentoring",
    "website": "https://futurpreneur.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person/Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "startup meeting"
  },
  {
    "name": "Youth For Entrepreneurship (Y4E)",
    "type": "Program",
    "category": "Business",
    "province": "Ontario",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "15-24",
    "skillsRequired": "Entrepreneurship Curiosity",
    "skillsGained": "Business Skills, Innovation, Leadership",
    "website": "https://www.ymcagta.org/youth-programs/y4e",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "young entrepreneurs"
  },
  {
    "name": "YELL Canada",
    "type": "Program",
    "category": "Business",
    "province": "National",
    "startDate": "September 2024",
    "endDate": "June 2025",
    "applicationDeadline": "August 2024",
    "ageRange": "14-18",
    "skillsRequired": "Business Interest",
    "skillsGained": "Entrepreneurship, Career Readiness, Business Acumen",
    "website": "https://yellcanada.org/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "business presentation"
  },
  {
    "name": "Edwards Entrepreneurship Summer Youth Camp",
    "type": "Camp",
    "category": "Business",
    "province": "Saskatchewan",
    "startDate": "July 2025",
    "endDate": "July 2025",
    "applicationDeadline": "May 2025",
    "ageRange": "9-14",
    "skillsRequired": "Interest in Business",
    "skillsGained": "Business Fundamentals, Entrepreneurship",
    "website": "https://www.edwards.usask.ca/entrepreneurshipexploration/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "summer camp"
  },
  {
    "name": "Brain Bee Canada",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "March 2025",
    "endDate": "May 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "13-18",
    "skillsRequired": "Neuroscience Interest",
    "skillsGained": "Neuroscience Knowledge, Scientific Thinking",
    "website": "https://www.brainbee.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "brain illustration"
  },
  {
    "name": "National Biology Competition (NBC)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "April 2025",
    "endDate": "April 2025",
    "applicationDeadline": "March 2025",
    "ageRange": "14-18",
    "skillsRequired": "Biology Knowledge",
    "skillsGained": "Biological Analysis, Scientific Reasoning",
    "website": "https://www.biology.utoronto.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "dna strand"
  },
  {
    "name": "Canadian Student Journalism Awards",
    "type": "Award",
    "category": "Arts",
    "province": "National",
    "startDate": "Year-round",
    "endDate": "September 2025",
    "applicationDeadline": "June 2025",
    "ageRange": "15-25",
    "skillsRequired": "Writing, Journalism",
    "skillsGained": "Journalism Skills, Writing, Media Literacy",
    "website": "https://j-schoolscanada.ca/",
    "competitive": true,
    "annual": true,
    "format": "Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "writing on notepad"
  },
  {
    "name": "Environment and Climate Change Youth Council",
    "type": "Council",
    "category": "Leadership",
    "province": "National",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling applications",
    "ageRange": "16-30",
    "skillsRequired": "Environmental Interest, Leadership",
    "skillsGained": "Policy Development, Environmental Action, Leadership",
    "website": "https://www.canada.ca/en/services/environment/weather/climatechange/get-involved/environment-climate-change-youth-council.html",
    "competitive": true,
    "annual": true,
    "format": "In-person/Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "environmental protest"
  },
  {
    "name": "Youth Climate Action Initiative",
    "type": "Program",
    "category": "Leadership",
    "province": "Ontario",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "16-25",
    "skillsRequired": "Environmental Passion",
    "skillsGained": "Climate Action, Sustainability, Leadership",
    "website": "https://skillsforchange.org/youth-climate-action-initiative",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "reforestation project"
  },
  {
    "name": "Canadian Youth Leadership Institute",
    "type": "Program",
    "category": "Leadership",
    "province": "National",
    "startDate": "Summer 2025",
    "endDate": "Summer 2025",
    "applicationDeadline": "Spring 2025",
    "ageRange": "14-17",
    "skillsRequired": "Leadership Interest",
    "skillsGained": "Leadership, Vision Setting, Personal Development",
    "website": "https://youthleadershipinstitute.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "leadership workshop"
  },
  {
    "name": "Rotary Youth Leadership Symposium (RYLS)",
    "type": "Program",
    "category": "Leadership",
    "province": "National",
    "startDate": "April 2025",
    "endDate": "April 2025",
    "applicationDeadline": "March 2025",
    "ageRange": "14-18",
    "skillsRequired": "Leadership Potential",
    "skillsGained": "Leadership, Communication, Community Service",
    "website": "https://rotary7070.org/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "team building"
  },
  {
    "name": "Canada World Youth",
    "type": "Program",
    "category": "Leadership",
    "province": "National",
    "startDate": "Various",
    "endDate": "Various",
    "applicationDeadline": "Rolling",
    "ageRange": "15-35",
    "skillsRequired": "Cultural Interest, Leadership",
    "skillsGained": "International Relations, Cultural Competence, Leadership",
    "website": "https://canadaworldyouth.org/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "global travel"
  },
  {
    "name": "Amnesty International Canada Youth Programs",
    "type": "Program",
    "category": "Community Service",
    "province": "National",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "Under 25",
    "skillsRequired": "Human Rights Interest",
    "skillsGained": "Human Rights Advocacy, Social Justice, Activism",
    "website": "https://amnesty.ca/what-you-can-do/youth-programs/",
    "competitive": false,
    "annual": true,
    "format": "In-person/Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "human rights"
  },
  {
    "name": "Global Leadership Academy Canada",
    "type": "Program",
    "category": "Leadership",
    "province": "British Columbia",
    "startDate": "July 2025",
    "endDate": "July 2025",
    "applicationDeadline": "May 2025",
    "ageRange": "15-18",
    "skillsRequired": "Leadership Interest",
    "skillsGained": "Global Leadership, Cultural Competence, Communication",
    "website": "https://www.powerfulyouth.org/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "global leaders"
  },
  {
    "name": "Science Bee Canada",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "Various",
    "endDate": "Various",
    "applicationDeadline": "School Registration Required",
    "ageRange": "13-18",
    "skillsRequired": "Science Knowledge",
    "skillsGained": "Scientific Knowledge, Quick Thinking, Competition Skills",
    "website": "https://ihbbcanada.com/science-bee",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "science quiz"
  },
  {
    "name": "Canadian International Music Competition",
    "type": "Competition",
    "category": "Arts",
    "province": "National",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "5-18",
    "skillsRequired": "Musical Talent",
    "skillsGained": "Musical Excellence, Performance Skills",
    "website": "https://www.cimconline.com/",
    "competitive": true,
    "annual": true,
    "format": "Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "piano performance"
  },
  {
    "name": "Wildlife Habitat Canada Art Competition",
    "type": "Competition",
    "category": "Arts",
    "province": "National",
    "startDate": "Fall 2024",
    "endDate": "Spring 2025",
    "applicationDeadline": "Winter 2025",
    "ageRange": "5-18",
    "skillsRequired": "Visual Arts Skills",
    "skillsGained": "Environmental Awareness, Artistic Skills",
    "website": "https://whc.org/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "wildlife painting"
  },
  {
    "name": "Young Canadians Parliament",
    "type": "Program",
    "category": "Leadership",
    "province": "National",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "Under 18",
    "skillsRequired": "Civic Interest",
    "skillsGained": "Democratic Process, Rights Education, Leadership",
    "website": "https://childrenfirstcanada.org/campaign/young-canadians-parliament/",
    "competitive": false,
    "annual": true,
    "format": "Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "youth parliament"
  },
  {
    "name": "SENgage Youth Program",
    "type": "Program",
    "category": "Leadership",
    "province": "National",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "14-30",
    "skillsRequired": "Civic Interest",
    "skillsGained": "Parliamentary Process, Civic Engagement",
    "website": "https://sencanada.ca/en/sengage/",
    "competitive": false,
    "annual": true,
    "format": "In-person/Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "senate chamber"
  },
  {
    "name": "Fryer, Galois, Hypatia Mathematics Contests",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "April 3, 2025",
    "endDate": "April 3, 2025",
    "applicationDeadline": "March 2025",
    "ageRange": "14-16",
    "skillsRequired": "Mathematics (Grades 9-11)",
    "skillsGained": "Mathematical Problem Solving, Critical Thinking",
    "website": "https://cemc.uwaterloo.ca/contests",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "math problems"
  },
  {
    "name": "Gauss Mathematics Contest",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "May 2025",
    "endDate": "May 2025",
    "applicationDeadline": "April 2025",
    "ageRange": "12-14",
    "skillsRequired": "Mathematics (Grades 7-8)",
    "skillsGained": "Problem Solving, Mathematical Reasoning",
    "website": "https://cemc.uwaterloo.ca/contests",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "math test"
  },
  {
    "name": "Canadian Intermediate Mathematics Contest (CIMC)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "November 2024",
    "endDate": "November 2024",
    "applicationDeadline": "October 2024",
    "ageRange": "15-16",
    "skillsRequired": "Mathematics (Grade 10)",
    "skillsGained": "Mathematical Problem Solving, Logic",
    "website": "https://cemc.uwaterloo.ca/contests",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "mathematics challenge"
  },
  {
    "name": "Canadian Senior Mathematics Contest (CSMC)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "November 2024",
    "endDate": "November 2024",
    "applicationDeadline": "October 2024",
    "ageRange": "16-18",
    "skillsRequired": "Mathematics (Grades 11-12)",
    "skillsGained": "Advanced Mathematical Reasoning, Problem Solving",
    "website": "https://cemc.uwaterloo.ca/contests",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "senior math"
  },
  {
    "name": "Canadian Team Mathematics Contest (CTMC)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "February 2025",
    "endDate": "February 2025",
    "applicationDeadline": "January 2025",
    "ageRange": "14-18",
    "skillsRequired": "Mathematics, Teamwork",
    "skillsGained": "Collaborative Problem Solving, Mathematical Communication",
    "website": "https://cemc.uwaterloo.ca/contests",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "team collaboration"
  },
  {
    "name": "Beaver Computing Challenge",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "November 2024",
    "endDate": "November 2024",
    "applicationDeadline": "October 2024",
    "ageRange": "10-18",
    "skillsRequired": "Computational Thinking",
    "skillsGained": "Programming Logic, Problem Solving",
    "website": "https://cemc.uwaterloo.ca/contests",
    "competitive": true,
    "annual": true,
    "format": "Online",
    "image": "https://placehold.co/600x400.png",
    "hint": "computer screen"
  },
  {
    "name": "Canadian Computing Olympiad (CCO)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "May 2025",
    "endDate": "May 2025",
    "applicationDeadline": "Based on CCC performance",
    "ageRange": "14-18",
    "skillsRequired": "Advanced Programming",
    "skillsGained": "Algorithm Design, Competitive Programming",
    "website": "https://cemc.uwaterloo.ca/contests/ccc",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "programming competition"
  },
  {
    "name": "Avogadro Chemistry Exam",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "May 15, 2025",
    "endDate": "May 15, 2025",
    "applicationDeadline": "May 2025",
    "ageRange": "16-17",
    "skillsRequired": "Chemistry (Grade 11)",
    "skillsGained": "Chemical Knowledge, Analytical Thinking",
    "website": "https://cemc.uwaterloo.ca/contests",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "chemistry exam"
  },
  {
    "name": "Chem 13 News Exam",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "May 8, 2025",
    "endDate": "May 8, 2025",
    "applicationDeadline": "May 2025",
    "ageRange": "17-18",
    "skillsRequired": "Chemistry (Grade 12)",
    "skillsGained": "Advanced Chemistry, Problem Solving",
    "website": "https://cemc.uwaterloo.ca/contests",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "chemistry test"
  },
  {
    "name": "Canadian Chemistry Olympiad (CCO)",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "Summer 2025",
    "endDate": "Summer 2025",
    "applicationDeadline": "Based on CCC performance",
    "ageRange": "16-18",
    "skillsRequired": "Advanced Chemistry",
    "skillsGained": "Laboratory Skills, Chemical Research",
    "website": "https://www.cheminst.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "chemistry olympiad"
  },
  {
    "name": "Amazon Future Engineer Your Voice is Power",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "School year",
    "endDate": "School year",
    "applicationDeadline": "During school year",
    "ageRange": "13-18",
    "skillsRequired": "Computer Science Interest",
    "skillsGained": "Computer Science, Entrepreneurship, Problem Solving",
    "website": "https://www.amazonfutureengineer.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person/Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "voice technology"
  },
  {
    "name": "FIRST LEGO League",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "October 2024",
    "endDate": "February 2025",
    "applicationDeadline": "September 2024",
    "ageRange": "9-16",
    "skillsRequired": "LEGO Building, Programming",
    "skillsGained": "Robotics, Engineering, Teamwork, Presentation",
    "website": "https://firstroboticscanada.org/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "lego robotics"
  },
  {
    "name": "FIRST Tech Challenge",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "September 2024",
    "endDate": "April 2025",
    "applicationDeadline": "August 2024",
    "ageRange": "12-18",
    "skillsRequired": "Engineering, Programming",
    "skillsGained": "Advanced Robotics, Engineering Design, Project Management",
    "website": "https://firstroboticscanada.org/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "robotics challenge"
  },
  {
    "name": "Skills Canada National Competition",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "May 2025",
    "endDate": "May 2025",
    "applicationDeadline": "Provincial qualifiers",
    "ageRange": "15-22",
    "skillsRequired": "Technical Skills",
    "skillsGained": "Trade Skills, Professional Development",
    "website": "https://www.skillscanada.com/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "trade skills"
  },
  {
    "name": "Envirothon Canada",
    "type": "Competition",
    "category": "STEM",
    "province": "National",
    "startDate": "Provincial competitions spring",
    "endDate": "National summer",
    "applicationDeadline": "Provincial registration",
    "ageRange": "14-18",
    "skillsRequired": "Environmental Science",
    "skillsGained": "Environmental Knowledge, Teamwork, Presentation",
    "website": "https://envirothon.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "environmental science"
  },
  {
    "name": "Canadian Geographic Challenge",
    "type": "Competition",
    "category": "Humanities",
    "province": "National",
    "startDate": "February 2025",
    "endDate": "May 2025",
    "applicationDeadline": "January 2025",
    "ageRange": "13-19",
    "skillsRequired": "Geography Knowledge",
    "skillsGained": "Geographic Literacy, Critical Thinking",
    "website": "https://canadiangeographic.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "world map"
  },
  {
    "name": "Historica Canada Fair",
    "type": "Competition",
    "category": "Humanities",
    "province": "National",
    "startDate": "Regional fairs spring",
    "endDate": "National fair summer",
    "applicationDeadline": "Regional deadlines",
    "ageRange": "11-18",
    "skillsRequired": "Historical Research",
    "skillsGained": "Research Skills, Presentation, Historical Analysis",
    "website": "https://www.historicacanada.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "history fair"
  },
  {
    "name": "Poetry In Voice National Recitation Contest",
    "type": "Competition",
    "category": "Arts",
    "province": "National",
    "startDate": "Regional competitions winter",
    "endDate": "National finals spring",
    "applicationDeadline": "Fall 2024",
    "ageRange": "13-20",
    "skillsRequired": "Public Speaking, Poetry",
    "skillsGained": "Public Speaking, Literature Appreciation, Performance",
    "website": "https://poetryinvoice.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "poetry reading"
  },
  {
    "name": "National Arts Centre Orchestra Young Artists Program",
    "type": "Program",
    "category": "Arts",
    "province": "National",
    "startDate": "Summer programs",
    "endDate": "Summer programs",
    "applicationDeadline": "Winter/Spring",
    "ageRange": "14-26",
    "skillsRequired": "Advanced Musical Skills",
    "skillsGained": "Musical Excellence, Performance Experience",
    "website": "https://nac-cna.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "orchestra performance"
  },
  {
    "name": "Canada Reads Student Challenge",
    "type": "Competition",
    "category": "Arts",
    "province": "National",
    "startDate": "Winter 2025",
    "endDate": "Spring 2025",
    "applicationDeadline": "Fall 2024",
    "ageRange": "15-18",
    "skillsRequired": "Reading, Critical Thinking",
    "skillsGained": "Literature Analysis, Debate Skills, Communication",
    "website": "https://www.cbc.ca/books/canadareads/",
    "competitive": true,
    "annual": true,
    "format": "Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "reading a book"
  },
  {
    "name": "DECA International Career Development Conference",
    "type": "Competition",
    "category": "Business",
    "province": "National",
    "startDate": "April 24, 2026",
    "endDate": "April 30, 2026",
    "applicationDeadline": "Qualify through provincials",
    "ageRange": "14-18",
    "skillsRequired": "Business Excellence",
    "skillsGained": "International Business, Leadership, Networking",
    "website": "https://deca.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "business conference"
  },
  {
    "name": "Junior Achievement Company Program",
    "type": "Program",
    "category": "Business",
    "province": "National",
    "startDate": "September 2024",
    "endDate": "May 2025",
    "applicationDeadline": "August 2024",
    "ageRange": "15-18",
    "skillsRequired": "Business Interest",
    "skillsGained": "Entrepreneurship, Business Operations, Leadership",
    "website": "https://jacanada.org/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "student business"
  },
  {
    "name": "National Economics Competition",
    "type": "Competition",
    "category": "Business",
    "province": "National",
    "startDate": "April 2025",
    "endDate": "April 2025",
    "applicationDeadline": "March 2025",
    "ageRange": "14-18",
    "skillsRequired": "Economics Knowledge",
    "skillsGained": "Economic Analysis, Critical Thinking",
    "website": "https://cea.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "economics graph"
  },
  {
    "name": "Startup Canada Learn Program",
    "type": "Program",
    "category": "Business",
    "province": "National",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "16-30",
    "skillsRequired": "Entrepreneurship Interest",
    "skillsGained": "Business Development, Networking, Innovation",
    "website": "https://startupcan.ca/",
    "competitive": false,
    "annual": true,
    "format": "Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "online learning"
  },
  {
    "name": "Young Entrepreneurs Organization (YEO) Global Student Entrepreneur Awards",
    "type": "Award",
    "category": "Business",
    "province": "National",
    "startDate": "Fall application period",
    "endDate": "Global finals",
    "applicationDeadline": "Fall 2024",
    "ageRange": "18-30",
    "skillsRequired": "Existing Business",
    "skillsGained": "Business Excellence, Global Networking",
    "website": "https://www.yeo.org/",
    "competitive": true,
    "annual": true,
    "format": "In-person/Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "entrepreneur award"
  },
  {
    "name": "National Youth Business Network",
    "type": "Network",
    "category": "Business",
    "province": "National",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "16-29",
    "skillsRequired": "Business Interest",
    "skillsGained": "Networking, Business Skills, Mentorship",
    "website": "https://nybn.ca/",
    "competitive": false,
    "annual": true,
    "format": "In-person/Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "business networking"
  },
  {
    "name": "Reach for the Top National Competition",
    "type": "Competition",
    "category": "Humanities",
    "province": "National",
    "startDate": "May 31, 2025",
    "endDate": "June 1, 2025",
    "applicationDeadline": "Provincial qualifiers",
    "ageRange": "14-18",
    "skillsRequired": "General Knowledge, Quick Recall",
    "skillsGained": "Trivia Knowledge, Team Collaboration, Quick Thinking",
    "website": "https://reachforthetop.com/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "quiz show"
  },
  {
    "name": "Expo-sciences Hydro-Québec",
    "type": "Competition",
    "category": "STEM",
    "province": "Quebec",
    "startDate": "April 11, 2025",
    "endDate": "April 13, 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "6-20",
    "skillsRequired": "Scientific Research, French/English",
    "skillsGained": "Scientific Method, Presentation, Innovation",
    "website": "https://technoscience.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "science project"
  },
  {
    "name": "Calgary Youth Science Fair",
    "type": "Competition",
    "category": "STEM",
    "province": "Alberta",
    "startDate": "April 10, 2025",
    "endDate": "April 12, 2025",
    "applicationDeadline": "February 7, 2025",
    "ageRange": "12-18",
    "skillsRequired": "Scientific Research, Presentation",
    "skillsGained": "Research Skills, Scientific Communication, Innovation",
    "website": "https://www.cysf.org/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "youth science"
  },
  {
    "name": "Skills Manitoba Competition",
    "type": "Competition",
    "category": "STEM",
    "province": "Manitoba",
    "startDate": "May 2025",
    "endDate": "May 2025",
    "applicationDeadline": "March 2025",
    "ageRange": "15-22",
    "skillsRequired": "Technical Skills, Trade Interest",
    "skillsGained": "Trade Skills, Professional Development, Competition Experience",
    "website": "https://skillsmanitoba.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "technical skills"
  },
  {
    "name": "Skills Canada Saskatchewan",
    "type": "Competition",
    "category": "STEM",
    "province": "Saskatchewan",
    "startDate": "April 2025",
    "endDate": "April 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "15-22",
    "skillsRequired": "Technical Skills",
    "skillsGained": "Trade Skills, Professional Development",
    "website": "https://www.skillscanadasask.com/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "welding competition"
  },
  {
    "name": "APEGA Science Olympics",
    "type": "Competition",
    "category": "STEM",
    "province": "Alberta",
    "startDate": "Spring 2025",
    "endDate": "Spring 2025",
    "applicationDeadline": "Winter 2025",
    "ageRange": "12-18",
    "skillsRequired": "Science Knowledge, Teamwork",
    "skillsGained": "Scientific Problem Solving, Team Collaboration",
    "website": "https://www.apega.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "science olympics"
  },
  {
    "name": "Junior Achievement British Columbia",
    "type": "Program",
    "category": "Business",
    "province": "British Columbia",
    "startDate": "September 2024",
    "endDate": "June 2025",
    "applicationDeadline": "August 2024",
    "ageRange": "14-18",
    "skillsRequired": "Business Interest",
    "skillsGained": "Entrepreneurship, Financial Literacy, Leadership",
    "website": "https://jabc.org/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "financial literacy"
  },
  {
    "name": "Ontario Science Centre Science Rendezvous",
    "type": "Program",
    "category": "STEM",
    "province": "Ontario",
    "startDate": "May 2025",
    "endDate": "May 2025",
    "applicationDeadline": "March 2025",
    "ageRange": "10-18",
    "skillsRequired": "Science Interest",
    "skillsGained": "Science Communication, Public Engagement",
    "website": "https://www.ontariosciencecentre.ca/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "science centre"
  },
  {
    "name": "Nova Scotia Science Fair",
    "type": "Competition",
    "category": "STEM",
    "province": "Nova Scotia",
    "startDate": "April 2025",
    "endDate": "April 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "12-18",
    "skillsRequired": "Scientific Research",
    "skillsGained": "Research Skills, Scientific Method, Presentation",
    "website": "https://www.nssf.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "science fair project"
  },
  {
    "name": "New Brunswick Science Fair",
    "type": "Competition",
    "category": "STEM",
    "province": "New Brunswick",
    "startDate": "April 2025",
    "endDate": "April 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "12-18",
    "skillsRequired": "Scientific Research",
    "skillsGained": "Research Methodology, Scientific Communication",
    "website": "https://www.nbsf.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "student research"
  },
  {
    "name": "Prince Edward Island Science Fair",
    "type": "Competition",
    "category": "STEM",
    "province": "Prince Edward Island",
    "startDate": "March 2025",
    "endDate": "March 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "12-18",
    "skillsRequired": "Scientific Research",
    "skillsGained": "Research Skills, Presentation, Innovation",
    "website": "https://www.peisf.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "science display"
  },
  {
    "name": "Newfoundland and Labrador Science Fair",
    "type": "Competition",
    "category": "STEM",
    "province": "Newfoundland and Labrador",
    "startDate": "April 2025",
    "endDate": "April 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "12-18",
    "skillsRequired": "Scientific Research",
    "skillsGained": "Research Skills, Scientific Communication",
    "website": "https://www.nlsf.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "research poster"
  },
  {
    "name": "Yukon Science Fair",
    "type": "Competition",
    "category": "STEM",
    "province": "Yukon",
    "startDate": "March 2025",
    "endDate": "March 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "12-18",
    "skillsRequired": "Scientific Research",
    "skillsGained": "Research Skills, Presentation",
    "website": "https://www.yukonsciencefair.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "northern lights"
  },
  {
    "name": "Northwest Territories Science Fair",
    "type": "Competition",
    "category": "STEM",
    "province": "Northwest Territories",
    "startDate": "March 2025",
    "endDate": "March 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "12-18",
    "skillsRequired": "Scientific Research",
    "skillsGained": "Research Skills, Scientific Method",
    "website": "https://www.nwtsf.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "arctic landscape"
  },
  {
    "name": "Nunavut Science Fair",
    "type": "Competition",
    "category": "STEM",
    "province": "Nunavut",
    "startDate": "April 2025",
    "endDate": "April 2025",
    "applicationDeadline": "March 2025",
    "ageRange": "12-18",
    "skillsRequired": "Scientific Research",
    "skillsGained": "Research Skills, Cultural Integration",
    "website": "https://www.nunavutsciencefair.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "inuit art"
  },
  {
    "name": "Ontario Youth Parliament",
    "type": "Program",
    "category": "Leadership",
    "province": "Ontario",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "16-25",
    "skillsRequired": "Civic Interest, Public Speaking",
    "skillsGained": "Parliamentary Procedure, Leadership, Public Policy",
    "website": "https://oyp.on.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "ontario legislature"
  },
  {
    "name": "Quebec Youth Parliament",
    "type": "Program",
    "category": "Leadership",
    "province": "Quebec",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "16-25",
    "skillsRequired": "French/English, Civic Interest",
    "skillsGained": "Parliamentary Procedure, Bilingual Communication, Leadership",
    "website": "https://pjq.qc.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "quebec parliament"
  },
  {
    "name": "Alberta Youth Parliament",
    "type": "Program",
    "category": "Leadership",
    "province": "Alberta",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "16-25",
    "skillsRequired": "Civic Interest, Leadership",
    "skillsGained": "Parliamentary Procedure, Public Speaking, Leadership",
    "website": "https://ayp.ab.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "alberta legislature"
  },
  {
    "name": "British Columbia Youth Parliament",
    "type": "Program",
    "category": "Leadership",
    "province": "British Columbia",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "16-25",
    "skillsRequired": "Civic Interest, Communication",
    "skillsGained": "Parliamentary Procedure, Leadership, Public Policy",
    "website": "https://bcyp.org/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "bc legislature"
  },
  {
    "name": "Manitoba Youth Parliament",
    "type": "Program",
    "category": "Leadership",
    "province": "Manitoba",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "16-25",
    "skillsRequired": "Civic Interest",
    "skillsGained": "Parliamentary Procedure, Leadership, Community Engagement",
    "website": "https://myp.mb.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "manitoba legislature"
  },
  {
    "name": "Saskatchewan Youth Parliament",
    "type": "Program",
    "category": "Leadership",
    "province": "Saskatchewan",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "16-25",
    "skillsRequired": "Civic Interest, Leadership",
    "skillsGained": "Parliamentary Procedure, Public Speaking, Leadership",
    "website": "https://syp.sk.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "saskatchewan legislature"
  },
  {
    "name": "Maritime Youth Parliament",
    "type": "Program",
    "category": "Leadership",
    "province": "Nova Scotia",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "16-25",
    "skillsRequired": "Civic Interest",
    "skillsGained": "Parliamentary Procedure, Regional Cooperation, Leadership",
    "website": "https://myp.ns.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "maritime coast"
  },
  {
    "name": "Indigenous Youth Leadership Program",
    "type": "Program",
    "category": "Leadership",
    "province": "National",
    "startDate": "Summer 2025",
    "endDate": "Summer 2025",
    "applicationDeadline": "Spring 2025",
    "ageRange": "14-24",
    "skillsRequired": "Indigenous Heritage, Leadership Interest",
    "skillsGained": "Cultural Leadership, Traditional Knowledge, Modern Leadership",
    "website": "https://www.afn.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "indigenous art"
  },
  {
    "name": "Concours de français Odyssée",
    "type": "Competition",
    "category": "Arts",
    "province": "National",
    "startDate": "March 2025",
    "endDate": "May 2025",
    "applicationDeadline": "February 2025",
    "ageRange": "12-18",
    "skillsRequired": "French Language",
    "skillsGained": "French Proficiency, Cultural Knowledge, Communication",
    "website": "https://www.acelf.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "french language"
  },
  {
    "name": "Toronto International Film Festival Student Programme",
    "type": "Program",
    "category": "Arts",
    "province": "Ontario",
    "startDate": "September 2025",
    "endDate": "September 2025",
    "applicationDeadline": "June 2025",
    "ageRange": "16-18",
    "skillsRequired": "Film Interest, Creativity",
    "skillsGained": "Film Analysis, Media Literacy, Cultural Awareness",
    "website": "https://www.tiff.net/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "film festival"
  },
  {
    "name": "Vancouver International Film Festival Youth Programme",
    "type": "Program",
    "category": "Arts",
    "province": "British Columbia",
    "startDate": "October 2025",
    "endDate": "October 2025",
    "applicationDeadline": "August 2025",
    "ageRange": "16-18",
    "skillsRequired": "Film Interest",
    "skillsGained": "Film Appreciation, Critical Thinking, Cultural Awareness",
    "website": "https://viff.org/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "movie theatre"
  },
  {
    "name": "Montreal Science Centre Youth Volunteer Program",
    "type": "Volunteering",
    "category": "Community Service",
    "province": "Quebec",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "14-18",
    "skillsRequired": "Science Interest, Bilingualism",
    "skillsGained": "Science Communication, Public Engagement, Bilingual Skills",
    "website": "https://www.montrealsciencecentre.com/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "science museum"
  },
  {
    "name": "Calgary Stampede Youth Programs",
    "type": "Program",
    "category": "Community Service",
    "province": "Alberta",
    "startDate": "July 2025",
    "endDate": "July 2025",
    "applicationDeadline": "May 2025",
    "ageRange": "14-18",
    "skillsRequired": "Community Interest",
    "skillsGained": "Event Management, Cultural Awareness, Leadership",
    "website": "https://www.calgarystampede.com/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "calgary stampede"
  },
  {
    "name": "Royal Ontario Museum Youth Programs",
    "type": "Program",
    "category": "Arts",
    "province": "Ontario",
    "startDate": "Year-round",
    "endDate": "Year-round",
    "applicationDeadline": "Rolling",
    "ageRange": "14-18",
    "skillsRequired": "Cultural Interest",
    "skillsGained": "Museum Studies, Cultural Knowledge, Public Engagement",
    "website": "https://www.rom.on.ca/",
    "competitive": false,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "museum exhibit"
  },
  {
    "name": "Manitoba Youth Climate Change Video Challenge",
    "type": "Competition",
    "category": "Leadership",
    "province": "Manitoba",
    "startDate": "Fall 2024",
    "endDate": "Spring 2025",
    "applicationDeadline": "Winter 2025",
    "ageRange": "13-18",
    "skillsRequired": "Video Production, Environmental Interest",
    "skillsGained": "Media Production, Environmental Awareness, Communication",
    "website": "https://climatechangeconnection.org/",
    "competitive": true,
    "annual": true,
    "format": "Virtual",
    "image": "https://placehold.co/600x400.png",
    "hint": "video production"
  },
  {
    "name": "Ontario Student Debate Association",
    "type": "Competition",
    "category": "Humanities",
    "province": "Ontario",
    "startDate": "September 2024",
    "endDate": "May 2025",
    "applicationDeadline": "August 2024",
    "ageRange": "14-18",
    "skillsRequired": "Public Speaking, Research",
    "skillsGained": "Debate Skills, Critical Thinking, Public Speaking",
    "website": "https://www.osda.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "student debate"
  },
  {
    "name": "Quebec Debate League",
    "type": "Competition",
    "category": "Humanities",
    "province": "Quebec",
    "startDate": "September 2024",
    "endDate": "May 2025",
    "applicationDeadline": "August 2024",
    "ageRange": "14-18",
    "skillsRequired": "French/English, Public Speaking",
    "skillsGained": "Bilingual Debate, Critical Thinking, Communication",
    "website": "https://www.debatquebec.org/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "public speaking"
  },
  {
    "name": "Alberta High School Debate Association",
    "type": "Competition",
    "category": "Humanities",
    "province": "Alberta",
    "startDate": "September 2024",
    "endDate": "May 2025",
    "applicationDeadline": "August 2024",
    "ageRange": "14-18",
    "skillsRequired": "Public Speaking, Research",
    "skillsGained": "Debate Skills, Research, Critical Analysis",
    "website": "https://www.ahsda.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "debate competition"
  },
  {
    "name": "British Columbia Student Debate Association",
    "type": "Competition",
    "category": "Humanities",
    "province": "British Columbia",
    "startDate": "September 2024",
    "endDate": "May 2025",
    "applicationDeadline": "August 2024",
    "ageRange": "14-18",
    "skillsRequired": "Public Speaking, Research",
    "skillsGained": "Debate Skills, Public Speaking, Critical Thinking",
    "website": "https://www.bcsda.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "students debating"
  },
  {
    "name": "Canadian National Debate Championship",
    "type": "Competition",
    "category": "Humanities",
    "province": "National",
    "startDate": "May 2025",
    "endDate": "May 2025",
    "applicationDeadline": "Provincial qualifiers",
    "ageRange": "14-18",
    "skillsRequired": "Advanced Debate Skills",
    "skillsGained": "National-level Debate, Leadership, Communication",
    "website": "https://www.cndc.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "debate championship"
  },
  {
    "name": "Remembrance Day Contests - Royal Canadian Legion",
    "type": "Competition",
    "category": "Arts",
    "province": "National",
    "startDate": "September 2024",
    "endDate": "November 2024",
    "applicationDeadline": "October 2024",
    "ageRange": "5-18",
    "skillsRequired": "Creative Writing, Visual Arts",
    "skillsGained": "Historical Awareness, Creative Expression, Civic Engagement",
    "website": "https://www.legion.ca/",
    "competitive": true,
    "annual": true,
    "format": "In-person",
    "image": "https://placehold.co/600x400.png",
    "hint": "remembrance day"
  }
]
