
export interface UniversityProgram {
  universityName: string;
  programName: string;
  province: string;
  faculty: string;
  minGradeAverage: string;
  requiredCourses: string;
  admissionType: string;
  earlyApplication: boolean;
  evaluationCriteria: string;
  preferredExtracurriculars: string;
  coopOption: boolean;
  website: string;
  image: string;
  hint: string;
}

export const programs: UniversityProgram[] = [
  {
    universityName: 'University of Toronto',
    programName: 'Computer Science',
    province: 'Ontario',
    faculty: 'Faculty of Arts & Science',
    minGradeAverage: '88-92%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: '70% grades + 30% supplementary application',
    preferredExtracurriculars: 'Programming competitions; robotics clubs; math contests; tech projects',
    coopOption: true,
    website: 'https://www.artsci.utoronto.ca/future/academics/programs-degrees/computer-science',
    image: 'https://placehold.co/600x400.png',
    hint: 'university campus'
  },
  {
    universityName: 'University of Toronto',
    programName: 'Life Sciences',
    province: 'Ontario',
    faculty: 'Faculty of Arts & Science',
    minGradeAverage: '85-88%',
    requiredCourses: 'English 4U, Biology 4U, Chemistry 4U, Advanced Functions 4U, one additional 4U course',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based with supplementary application',
    preferredExtracurriculars: 'Research experience; science olympiad; lab volunteering; environmental clubs',
    coopOption: true,
    website: 'https://www.artsci.utoronto.ca/future/academics/programs-degrees/life-sciences',
    image: 'https://placehold.co/600x400.png',
    hint: 'science lab'
  },
  {
    universityName: 'University of Toronto',
    programName: 'Commerce (Rotman)',
    province: 'Ontario',
    faculty: 'Rotman School of Management',
    minGradeAverage: '92-95%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Highly Competitive',
    earlyApplication: false,
    evaluationCriteria: '50% grades + 50% supplementary application (essays + video)',
    preferredExtracurriculars: 'Leadership roles; business competitions; entrepreneurship; community service',
    coopOption: true,
    website: 'https://rotmancommerce.utoronto.ca/admissions',
    image: 'https://placehold.co/600x400.png',
    hint: 'business school'
  },
  {
    universityName: 'University of Toronto',
    programName: 'Engineering Science',
    province: 'Ontario',
    faculty: 'Faculty of Applied Science & Engineering',
    minGradeAverage: '93-96%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, Chemistry 4U, Physics 4U',
    admissionType: 'Highly Competitive',
    earlyApplication: false,
    evaluationCriteria: '75% grades + 25% supplementary application',
    preferredExtracurriculars: 'Science fairs; research projects; engineering competitions; STEM leadership',
    coopOption: true,
    website: 'https://engsci.utoronto.ca/admissions/',
    image: 'https://placehold.co/600x400.png',
    hint: 'engineering building'
  },
  {
    universityName: 'University of British Columbia',
    programName: 'Computer Science',
    province: 'British Columbia',
    faculty: 'Faculty of Science',
    minGradeAverage: '88-92%',
    requiredCourses: 'English 12, Pre-Calculus 12, Chemistry 12 or Physics 12, one additional Grade 12 course',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Academic performance + personal profile',
    preferredExtracurriculars: 'Programming projects; hackathons; tech volunteering; computer clubs',
    coopOption: true,
    website: 'https://www.cs.ubc.ca/students/undergrad/admission',
    image: 'https://placehold.co/600x400.png',
    hint: 'university campus'
  },
  {
    universityName: 'University of British Columbia',
    programName: 'Commerce (Sauder)',
    province: 'British Columbia',
    faculty: 'Sauder School of Business',
    minGradeAverage: '89-93%',
    requiredCourses: 'English 12, Pre-Calculus 12, 2 additional Grade 12 courses',
    admissionType: 'Highly Competitive',
    earlyApplication: false,
    evaluationCriteria: '40% grades + 60% personal profile + video interview',
    preferredExtracurriculars: 'Leadership; business experience; community involvement; entrepreneurship',
    coopOption: true,
    website: 'https://www.sauder.ubc.ca/programs/bachelor-commerce/admissions',
    image: 'https://placehold.co/600x400.png',
    hint: 'modern building'
  },
  {
    universityName: 'University of British Columbia',
    programName: 'Engineering',
    province: 'British Columbia',
    faculty: 'Faculty of Applied Science',
    minGradeAverage: '87-91%',
    requiredCourses: 'English 12, Pre-Calculus 12, Chemistry 12, Physics 12',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Academic performance + personal profile',
    preferredExtracurriculars: 'Engineering competitions; robotics; science projects; technical leadership',
    coopOption: true,
    website: 'https://www.apsc.ubc.ca/admissions',
    image: 'https://placehold.co/600x400.png',
    hint: 'engineering workshop'
  },
  {
    universityName: 'University of British Columbia',
    programName: 'Kinesiology',
    province: 'British Columbia',
    faculty: 'Faculty of Education',
    minGradeAverage: '83-87%',
    requiredCourses: 'English 12, Pre-Calculus 12, Biology 12, Chemistry 12 or Physics 12',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Academic performance + personal profile',
    preferredExtracurriculars: 'Sports participation; coaching; health-related volunteering; fitness leadership',
    coopOption: true,
    website: 'https://kin.educ.ubc.ca/undergraduate-programs/admissions/',
    image: 'https://placehold.co/600x400.png',
    hint: 'sports facility'
  },
  {
    universityName: 'McGill University',
    programName: 'Computer Science',
    province: 'Quebec',
    faculty: 'Faculty of Science',
    minGradeAverage: '89-93%',
    requiredCourses: 'English, Advanced Functions, Calculus, Chemistry or Physics, one additional academic course',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming competitions; tech projects; math contests; computer science clubs',
    coopOption: true,
    website: 'https://www.mcgill.ca/study/2023-2024/faculties/science/undergraduate/programs/bachelor-science-bsc-major-computer-science',
    image: 'https://placehold.co/600x400.png',
    hint: 'historic architecture'
  },
  {
    universityName: 'McGill University',
    programName: 'Commerce',
    province: 'Quebec',
    faculty: 'Desautels Faculty of Management',
    minGradeAverage: '91-95%',
    requiredCourses: 'English, Advanced Functions, Calculus, 2 additional academic courses',
    admissionType: 'Highly Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Grades-based with holistic review',
    preferredExtracurriculars: 'Leadership roles; business competitions; community service; international experience',
    coopOption: false,
    website: 'https://www.mcgill.ca/desautels/programs/bcom',
    image: 'https://placehold.co/600x400.png',
    hint: 'business lecture'
  },
  {
    universityName: 'McGill University',
    programName: 'Life Sciences',
    province: 'Quebec',
    faculty: 'Faculty of Science',
    minGradeAverage: '87-91%',
    requiredCourses: 'English, Biology, Chemistry, Advanced Functions, one additional academic course',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Research experience; science competitions; lab volunteering; environmental activities',
    coopOption: true,
    website: 'https://www.mcgill.ca/study/2023-2024/faculties/science/undergraduate/programs/bachelor-science-bsc-major-biology',
    image: 'https://placehold.co/600x400.png',
    hint: 'biology research'
  },
  {
    universityName: 'McGill University',
    programName: 'Engineering',
    province: 'Quebec',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '88-92%',
    requiredCourses: 'English, Advanced Functions, Calculus, Chemistry, Physics',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; robotics clubs; science fairs; technical projects',
    coopOption: true,
    website: 'https://www.mcgill.ca/engineering/students/undergraduate/admissions',
    image: 'https://placehold.co/600x400.png',
    hint: 'engineering students'
  },
  {
    universityName: 'University of Waterloo',
    programName: 'Computer Science',
    province: 'Ontario',
    faculty: 'Faculty of Mathematics',
    minGradeAverage: '95-97%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Highly Competitive',
    earlyApplication: false,
    evaluationCriteria: '75% admission average + 25% Admission Information Form',
    preferredExtracurriculars: 'Programming contests; hackathons; open source contributions; math competitions',
    coopOption: true,
    website: 'https://uwaterloo.ca/future-students/programs/computer-science',
    image: 'https://placehold.co/600x400.png',
    hint: 'coding on screen'
  },
  {
    universityName: 'University of Waterloo',
    programName: 'Software Engineering',
    province: 'Ontario',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '94-96%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, Chemistry 4U, Physics 4U',
    admissionType: 'Highly Competitive',
    earlyApplication: false,
    evaluationCriteria: '75% admission average + 25% Admission Information Form',
    preferredExtracurriculars: 'Programming projects; engineering competitions; robotics; leadership in STEM',
    coopOption: true,
    website: 'https://uwaterloo.ca/future-students/programs/software-engineering',
    image: 'https://placehold.co/600x400.png',
    hint: 'software development'
  },
  {
    universityName: 'University of Waterloo',
    programName: 'Accounting and Financial Management',
    province: 'Ontario',
    faculty: 'School of Accounting and Finance',
    minGradeAverage: '90-93%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Highly Competitive',
    earlyApplication: false,
    evaluationCriteria: '75% admission average + 25% Admission Information Form',
    preferredExtracurriculars: 'Business competitions; accounting clubs; finance internships; leadership roles',
    coopOption: true,
    website: 'https://uwaterloo.ca/future-students/programs/accounting-and-financial-management',
    image: 'https://placehold.co/600x400.png',
    hint: 'financial charts'
  },
  {
    universityName: 'University of Waterloo',
    programName: 'Engineering (General)',
    province: 'Ontario',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '90-94%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, Chemistry 4U, Physics 4U',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: '75% admission average + 25% Admission Information Form',
    preferredExtracurriculars: 'Engineering design teams; robotics; science fairs; technical leadership',
    coopOption: true,
    website: 'https://uwaterloo.ca/future-students/programs/engineering',
    image: 'https://placehold.co/600x400.png',
    hint: 'engineering students collaborating'
  },
  {
    universityName: 'McMaster University',
    programName: 'Health Sciences',
    province: 'Ontario',
    faculty: 'Faculty of Health Sciences',
    minGradeAverage: '95%+',
    requiredCourses: 'English 4U, Biology 4U, Chemistry 4U, Advanced Functions 4U, one additional 4U course',
    admissionType: 'Highly Competitive',
    earlyApplication: false,
    evaluationCriteria: '25% grades + 75% supplementary application (CASPer test + essays)',
    preferredExtracurriculars: 'Healthcare volunteering; research experience; leadership in health; community service',
    coopOption: false,
    website: 'https://healthsci.mcmaster.ca/admissions',
    image: 'https://placehold.co/600x400.png',
    hint: 'health science lab'
  },
  {
    universityName: 'McMaster University',
    programName: 'Engineering',
    province: 'Ontario',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '88-92%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, Chemistry 4U, Physics 4U',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: '70% grades + 30% supplementary application',
    preferredExtracurriculars: 'Engineering competitions; robotics teams; design projects; STEM leadership',
    coopOption: true,
    website: 'https://www.eng.mcmaster.ca/future-students/undergraduate-admissions',
    image: 'https://placehold.co/600x400.png',
    hint: 'engineering design'
  },
  {
    universityName: 'McMaster University',
    programName: 'Integrated Science (iSci)',
    province: 'Ontario',
    faculty: 'Faculty of Science',
    minGradeAverage: '90-93%',
    requiredCourses: 'English 4U, Biology 4U, Chemistry 4U, Advanced Functions 4U, Calculus & Vectors 4U, Physics 4U',
    admissionType: 'Highly Competitive',
    earlyApplication: false,
    evaluationCriteria: '50% grades + 50% supplementary application',
    preferredExtracurriculars: 'Research experience; interdisciplinary projects; science competitions; innovation',
    coopOption: false,
    website: 'https://www.science.mcmaster.ca/isci/',
    image: 'https://placehold.co/600x400.png',
    hint: 'interdisciplinary science'
  },
  {
    universityName: 'McMaster University',
    programName: 'Commerce',
    province: 'Ontario',
    faculty: 'DeGroote School of Business',
    minGradeAverage: '87-91%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: '70% grades + 30% supplementary application',
    preferredExtracurriculars: 'Leadership roles; business clubs; entrepreneurship; community involvement',
    coopOption: true,
    website: 'https://www.degroote.mcmaster.ca/programs/undergraduate-programs/bachelor-of-commerce/',
    image: 'https://placehold.co/600x400.png',
    hint: 'business students'
  },
  {
    universityName: "Queen's University",
    programName: 'Commerce',
    province: 'Ontario',
    faculty: 'Smith School of Business',
    minGradeAverage: '90-93%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Highly Competitive',
    earlyApplication: true,
    evaluationCriteria: '60% grades + 40% supplementary application (PSE)',
    preferredExtracurriculars: 'Leadership experience; business competitions; community service; international experience',
    coopOption: true,
    website: 'https://smith.queensu.ca/bcom/',
    image: 'https://placehold.co/600x400.png',
    hint: 'historic university'
  },
  {
    universityName: "Queen's University",
    programName: 'Engineering',
    province: 'Ontario',
    faculty: 'Faculty of Engineering and Applied Science',
    minGradeAverage: '88-92%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, Chemistry 4U, Physics 4U',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: '75% grades + 25% Personal Statement of Experience (PSE)',
    preferredExtracurriculars: 'Engineering competitions; robotics; design projects; technical leadership',
    coopOption: true,
    website: 'https://www.queensu.ca/admission/programs/engineering',
    image: 'https://placehold.co/600x400.png',
    hint: 'engineering students'
  },
  {
    universityName: "Queen's University",
    programName: 'Computer Science',
    province: 'Ontario',
    faculty: 'Faculty of Arts and Science',
    minGradeAverage: '87-91%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based with PSE',
    preferredExtracurriculars: 'Programming contests; hackathons; math competitions; tech volunteering',
    coopOption: false,
    website: 'https://www.cs.queensu.ca/undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'computer lab'
  },
  {
    universityName: "Queen's University",
    programName: 'Life Sciences',
    province: 'Ontario',
    faculty: 'Faculty of Arts and Science',
    minGradeAverage: '85-89%',
    requiredCourses: 'English 4U, Biology 4U, Chemistry 4U, Advanced Functions 4U, one additional 4U course',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based with PSE',
    preferredExtracurriculars: 'Research experience; science olympiad; lab volunteering; environmental clubs',
    coopOption: false,
    website: 'https://www.queensu.ca/admission/programs/life-sciences',
    image: 'https://placehold.co/600x400.png',
    hint: 'science students'
  },
  {
    universityName: 'Western University',
    programName: 'Business (Ivey HBA)',
    province: 'Ontario',
    faculty: 'Ivey Business School',
    minGradeAverage: '85%+',
    requiredCourses: 'Any 4U/M courses for Year 1 entry',
    admissionType: 'Two-stage (AEO status, then HBA)',
    earlyApplication: true,
    evaluationCriteria: 'AEO: grades + extracurriculars + essays; HBA: Ivey academic performance + leadership',
    preferredExtracurriculars: 'Exceptional leadership; business experience; community impact; international experience',
    coopOption: true,
    website: 'https://www.ivey.uwo.ca/hba/admissions/',
    image: 'https://placehold.co/600x400.png',
    hint: 'business meeting'
  },
  {
    universityName: 'Western University',
    programName: 'Engineering',
    province: 'Ontario',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '85-89%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, Chemistry 4U, Physics 4U',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; design teams; robotics; technical projects',
    coopOption: true,
    website: 'https://www.eng.uwo.ca/undergraduate/future-students/',
    image: 'https://placehold.co/600x400.png',
    hint: 'engineering design'
  },
  {
    universityName: 'Western University',
    programName: 'Computer Science',
    province: 'Ontario',
    faculty: 'Faculty of Science',
    minGradeAverage: '83-87%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming competitions; hackathons; computer clubs; tech projects',
    coopOption: true,
    website: 'https://www.csd.uwo.ca/undergraduate/index.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'computer programming'
  },
  {
    universityName: 'Western University',
    programName: 'Medical Science',
    province: 'Ontario',
    faculty: 'Faculty of Science',
    minGradeAverage: '87-91%',
    requiredCourses: 'English 4U, Biology 4U, Chemistry 4U, Advanced Functions 4U, one additional 4U course',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Research experience; healthcare volunteering; science competitions; lab experience',
    coopOption: false,
    website: 'https://www.uwo.ca/sci/undergraduate/programs/medical_science.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'medical research'
  },
  {
    universityName: 'University of Alberta',
    programName: 'Engineering',
    province: 'Alberta',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '85-89%',
    requiredCourses: 'English 30-1, Math 30-1, Chemistry 30, Physics 30, one additional 30-level course',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; robotics; science projects; technical leadership',
    coopOption: true,
    website: 'https://www.ualberta.ca/engineering/student-services/prospective-students/',
    image: 'https://placehold.co/600x400.png',
    hint: 'university campus'
  },
  {
    universityName: 'University of Alberta',
    programName: 'Computer Science',
    province: 'Alberta',
    faculty: 'Faculty of Science',
    minGradeAverage: '82-86%',
    requiredCourses: 'English 30-1, Math 30-1, 2 additional 30-level courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming competitions; hackathons; computer clubs; math contests',
    coopOption: true,
    website: 'https://www.ualberta.ca/computing-science/undergraduate-studies/prospective-students/',
    image: 'https://placehold.co/600x400.png',
    hint: 'coding on laptop'
  },
  {
    universityName: 'University of Alberta',
    programName: 'Business',
    province: 'Alberta',
    faculty: 'Alberta School of Business',
    minGradeAverage: '83-87%',
    requiredCourses: 'English 30-1, Math 30-1, 2 additional 30-level courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Leadership roles; business competitions; entrepreneurship; community service',
    coopOption: true,
    website: 'https://www.ualberta.ca/business/programs/bachelor-of-commerce/',
    image: 'https://placehold.co/600x400.png',
    hint: 'business students'
  },
  {
    universityName: 'University of Alberta',
    programName: 'Nursing',
    province: 'Alberta',
    faculty: 'Faculty of Nursing',
    minGradeAverage: '85-89%',
    requiredCourses: 'English 30-1, Math 30-1, Biology 30, Chemistry 30, one additional 30-level course',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: '75% grades + 25% non-academic requirements',
    preferredExtracurriculars: 'Healthcare volunteering; leadership; community service; healthcare experience',
    coopOption: false,
    website: 'https://www.ualberta.ca/nursing/programs/bachelor-of-science-in-nursing/',
    image: 'https://placehold.co/600x400.png',
    hint: 'nursing students'
  },
  {
    universityName: 'York University',
    programName: 'Computer Science',
    province: 'Ontario',
    faculty: 'Faculty of Science',
    minGradeAverage: '80-84%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming projects; hackathons; computer clubs; tech volunteering',
    coopOption: true,
    website: 'https://lassonde.yorku.ca/computer-science',
    image: 'https://placehold.co/600x400.png',
    hint: 'university building'
  },
  {
    universityName: 'York University',
    programName: 'Business Administration',
    province: 'Ontario',
    faculty: 'Schulich School of Business',
    minGradeAverage: '87-91%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: '50% grades + 50% supplementary application',
    preferredExtracurriculars: 'Leadership experience; business competitions; community service; international experience',
    coopOption: true,
    website: 'https://schulich.yorku.ca/programs/undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'business school building'
  },
  {
    universityName: 'York University',
    programName: 'Engineering',
    province: 'Ontario',
    faculty: 'Lassonde School of Engineering',
    minGradeAverage: '82-86%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, Chemistry 4U, Physics 4U',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; robotics; design projects; STEM activities',
    coopOption: true,
    website: 'https://lassonde.yorku.ca/admissions/',
    image: 'https://placehold.co/600x400.png',
    hint: 'engineering lab'
  },
  {
    universityName: 'York University',
    programName: 'Kinesiology',
    province: 'Ontario',
    faculty: 'Faculty of Health',
    minGradeAverage: '78-82%',
    requiredCourses: 'English 4U, Biology 4U, one of Chemistry 4U/Physics 4U, Advanced Functions 4U, one additional 4U course',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Sports participation; coaching; health-related volunteering; fitness leadership',
    coopOption: false,
    website: 'https://health.yorku.ca/kinesiology-health-science/',
    image: 'https://placehold.co/600x400.png',
    hint: 'fitness center'
  },
  {
    universityName: 'Toronto Metropolitan University',
    programName: 'Engineering',
    province: 'Ontario',
    faculty: 'Faculty of Engineering and Architectural Science',
    minGradeAverage: '82-86%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, Chemistry 4U, Physics 4U',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; design projects; robotics; technical activities',
    coopOption: true,
    website: 'https://www.torontomet.ca/engineering/',
    image: 'https://placehold.co/600x400.png',
    hint: 'city campus'
  },
  {
    universityName: 'Toronto Metropolitan University',
    programName: 'Business Management',
    province: 'Ontario',
    faculty: 'Ted Rogers School of Management',
    minGradeAverage: '80-84%',
    requiredCourses: 'English 4U, Advanced Functions 4U, 3 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Leadership roles; business activities; entrepreneurship; community service',
    coopOption: true,
    website: 'https://www.torontomet.ca/trsm-undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'modern architecture'
  },
  {
    universityName: 'Toronto Metropolitan University',
    programName: 'Computer Science',
    province: 'Ontario',
    faculty: 'Faculty of Science',
    minGradeAverage: '83-87%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming projects; hackathons; computer clubs; tech competitions',
    coopOption: true,
    website: 'https://www.torontomet.ca/programs/undergraduate/computer-science/',
    image: 'https://placehold.co/600x400.png',
    hint: 'downtown campus'
  },
  {
    universityName: 'Toronto Metropolitan University',
    programName: 'Nursing',
    province: 'Ontario',
    faculty: 'Faculty of Community Services',
    minGradeAverage: '84-88%',
    requiredCourses: 'English 4U, Biology 4U, Chemistry 4U, Advanced Functions 4U, one additional 4U course',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: '70% grades + 30% supplementary application',
    preferredExtracurriculars: 'Healthcare volunteering; leadership; community service; healthcare experience',
    coopOption: false,
    website: 'https://www.torontomet.ca/programs/undergraduate/nursing/',
    image: 'https://placehold.co/600x400.png',
    hint: 'nursing students'
  },
  {
    universityName: 'Carleton University',
    programName: 'Computer Science',
    province: 'Ontario',
    faculty: 'Faculty of Science',
    minGradeAverage: '81-85%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming competitions; hackathons; computer clubs; math contests',
    coopOption: true,
    website: 'https://carleton.ca/scs/undergraduate-programs/',
    image: 'https://placehold.co/600x400.png',
    hint: 'university library'
  },
  {
    universityName: 'Carleton University',
    programName: 'Engineering',
    province: 'Ontario',
    faculty: 'Faculty of Engineering and Design',
    minGradeAverage: '83-87%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, Chemistry 4U, Physics 4U',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; design teams; robotics; technical projects',
    coopOption: true,
    website: 'https://carleton.ca/engineering-design/',
    image: 'https://placehold.co/600x400.png',
    hint: 'engineering building'
  },
  {
    universityName: 'Carleton University',
    programName: 'Business',
    province: 'Ontario',
    faculty: 'Sprott School of Business',
    minGradeAverage: '79-83%',
    requiredCourses: 'English 4U, Advanced Functions 4U, 3 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Leadership roles; business competitions; entrepreneurship; community involvement',
    coopOption: true,
    website: 'https://sprott.carleton.ca/undergraduate-programs/',
    image: 'https://placehold.co/600x400.png',
    hint: 'business campus'
  },
  {
    universityName: 'Carleton University',
    programName: 'Journalism',
    province: 'Ontario',
    faculty: 'Faculty of Public Affairs',
    minGradeAverage: '82-86%',
    requiredCourses: 'English 4U, 4 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: '50% grades + 50% portfolio and interview',
    preferredExtracurriculars: 'Writing portfolio; media experience; communications activities; current events knowledge',
    coopOption: false,
    website: 'https://carleton.ca/journalism/undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'journalism student'
  },
  {
    universityName: 'University of Ottawa',
    programName: 'Engineering',
    province: 'Ontario',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '84-88%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, Chemistry 4U, Physics 4U',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; design projects; robotics; bilingual skills valued',
    coopOption: true,
    website: 'https://engineering.uottawa.ca/undergraduate-programs',
    image: 'https://placehold.co/600x400.png',
    hint: 'university campus'
  },
  {
    universityName: 'University of Ottawa',
    programName: 'Computer Science',
    province: 'Ontario',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '82-86%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming competitions; hackathons; computer clubs; bilingual skills valued',
    coopOption: true,
    website: 'https://www.uottawa.ca/faculty-engineering/undergraduate-programs/computer-science',
    image: 'https://placehold.co/600x400.png',
    hint: 'coding students'
  },
  {
    universityName: 'University of Ottawa',
    programName: 'Commerce',
    province: 'Ontario',
    faculty: 'Telfer School of Management',
    minGradeAverage: '81-85%',
    requiredCourses: 'English 4U, Advanced Functions 4U, 3 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Leadership roles; business competitions; bilingual skills; international experience',
    coopOption: true,
    website: 'https://telfer.uottawa.ca/en/programs/undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'business students'
  },
  {
    universityName: 'University of Ottawa',
    programName: 'Health Sciences',
    province: 'Ontario',
    faculty: 'Faculty of Health Sciences',
    minGradeAverage: '87-91%',
    requiredCourses: 'English 4U, Biology 4U, Chemistry 4U, Advanced Functions 4U, one additional 4U course',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Healthcare volunteering; research experience; community service; bilingual skills valued',
    coopOption: false,
    website: 'https://health.uottawa.ca/undergraduate-programs/',
    image: 'https://placehold.co/600x400.png',
    hint: 'health science lab'
  },
  {
    universityName: 'Simon Fraser University',
    programName: 'Computer Science',
    province: 'British Columbia',
    faculty: 'Faculty of Applied Sciences',
    minGradeAverage: '85-89%',
    requiredCourses: 'English 12, Pre-Calculus 12, 2 additional Grade 12 courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Academic performance + personal profile',
    preferredExtracurriculars: 'Programming competitions; hackathons; tech projects; computer clubs',
    coopOption: true,
    website: 'https://www.sfu.ca/computing/prospective-students/undergraduate-students.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'mountain campus'
  },
  {
    universityName: 'Simon Fraser University',
    programName: 'Engineering Science',
    province: 'British Columbia',
    faculty: 'Faculty of Applied Sciences',
    minGradeAverage: '83-87%',
    requiredCourses: 'English 12, Pre-Calculus 12, Chemistry 12, Physics 12',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Academic performance + personal profile',
    preferredExtracurriculars: 'Engineering competitions; robotics; science projects; technical leadership',
    coopOption: true,
    website: 'https://www.sfu.ca/engineering/prospective-students/undergraduate-programs.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'engineering students'
  },
  {
    universityName: 'Simon Fraser University',
    programName: 'Business Administration',
    province: 'British Columbia',
    faculty: 'Beedie School of Business',
    minGradeAverage: '82-86%',
    requiredCourses: 'English 12, Pre-Calculus 12, 2 additional Grade 12 courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Academic performance + personal profile',
    preferredExtracurriculars: 'Leadership experience; business competitions; entrepreneurship; community service',
    coopOption: true,
    website: 'https://beedie.sfu.ca/programs/undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'modern architecture'
  },
  {
    universityName: 'Simon Fraser University',
    programName: 'Kinesiology',
    province: 'British Columbia',
    faculty: 'Faculty of Science',
    minGradeAverage: '80-84%',
    requiredCourses: 'English 12, Biology 12, Chemistry 12 or Physics 12, Pre-Calculus 12',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Academic performance + personal profile',
    preferredExtracurriculars: 'Sports participation; coaching; health-related activities; fitness leadership',
    coopOption: false,
    website: 'https://www.sfu.ca/biomedical-physiology-kinesiology/prospective-students/undergraduate.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'gymnastics'
  },
  {
    universityName: 'Dalhousie University',
    programName: 'Engineering',
    province: 'Nova Scotia',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '80-84%',
    requiredCourses: 'English 12, Pre-Calculus 12, Chemistry 12, Physics 12',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; design projects; robotics; maritime industry experience',
    coopOption: true,
    website: 'https://www.dal.ca/faculty/engineering/programs/undergraduate.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'coastal university'
  },
  {
    universityName: 'Dalhousie University',
    programName: 'Computer Science',
    province: 'Nova Scotia',
    faculty: 'Faculty of Computer Science',
    minGradeAverage: '81-85%',
    requiredCourses: 'English 12, Pre-Calculus 12, 2 additional Grade 12 courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming competitions; hackathons; computer clubs; tech volunteering',
    coopOption: true,
    website: 'https://www.cs.dal.ca/undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'computer lab'
  },
  {
    universityName: 'Dalhousie University',
    programName: 'Commerce',
    province: 'Nova Scotia',
    faculty: 'Faculty of Management',
    minGradeAverage: '78-82%',
    requiredCourses: 'English 12, Pre-Calculus 12, 2 additional Grade 12 courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Leadership roles; business activities; community service; maritime business experience',
    coopOption: true,
    website: 'https://www.dal.ca/faculty/management/programs/undergraduate.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'business students'
  },
  {
    universityName: 'Dalhousie University',
    programName: 'Health Sciences',
    province: 'Nova Scotia',
    faculty: 'Faculty of Health',
    minGradeAverage: '83-87%',
    requiredCourses: 'English 12, Biology 12, Chemistry 12, Pre-Calculus 12',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Healthcare volunteering; research experience; community service; health-related leadership',
    coopOption: false,
    website: 'https://www.dal.ca/faculty/health/programs/undergraduate.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'health research'
  },
  {
    universityName: 'University of Calgary',
    programName: 'Engineering',
    province: 'Alberta',
    faculty: 'Schulich School of Engineering',
    minGradeAverage: '83-87%',
    requiredCourses: 'English 30-1, Math 30-1, Chemistry 30, Physics 30',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; robotics; energy sector projects; technical leadership',
    coopOption: true,
    website: 'https://schulich.ucalgary.ca/future-students/undergraduate/admissions',
    image: 'https://placehold.co/600x400.png',
    hint: 'city skyline'
  },
  {
    universityName: 'University of Calgary',
    programName: 'Computer Science',
    province: 'Alberta',
    faculty: 'Faculty of Science',
    minGradeAverage: '81-85%',
    requiredCourses: 'English 30-1, Math 30-1, 2 additional 30-level courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming competitions; hackathons; computer clubs; tech industry experience',
    coopOption: true,
    website: 'https://www.ucalgary.ca/future-students/undergraduate/explore-programs/computer-science',
    image: 'https://placehold.co/600x400.png',
    hint: 'modern campus'
  },
  {
    universityName: 'University of Calgary',
    programName: 'Business',
    province: 'Alberta',
    faculty: 'Haskayne School of Business',
    minGradeAverage: '80-84%',
    requiredCourses: 'English 30-1, Math 30-1, 2 additional 30-level courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Leadership roles; business competitions; entrepreneurship; energy industry experience',
    coopOption: true,
    website: 'https://haskayne.ucalgary.ca/programs/undergraduate/bachelor-commerce',
    image: 'https://placehold.co/600x400.png',
    hint: 'business building'
  },
  {
    universityName: 'University of Calgary',
    programName: 'Kinesiology',
    province: 'Alberta',
    faculty: 'Faculty of Kinesiology',
    minGradeAverage: '82-86%',
    requiredCourses: 'English 30-1, Biology 30, Chemistry 30, Math 30-1',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Sports participation; coaching; health/fitness activities; research experience',
    coopOption: false,
    website: 'https://kinesiology.ucalgary.ca/undergraduate/future-students',
    image: 'https://placehold.co/600x400.png',
    hint: 'sports science'
  },
  {
    universityName: 'University of Manitoba',
    programName: 'Engineering',
    province: 'Manitoba',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '80-84%',
    requiredCourses: 'English 40S, Math 40S (Pre-Calculus), Chemistry 40S, Physics 40S',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; design projects; robotics; technical activities',
    coopOption: true,
    website: 'https://umanitoba.ca/engineering/',
    image: 'https://placehold.co/600x400.png',
    hint: 'university campus'
  },
  {
    universityName: 'University of Manitoba',
    programName: 'Computer Science',
    province: 'Manitoba',
    faculty: 'Faculty of Science',
    minGradeAverage: '78-82%',
    requiredCourses: 'English 40S, Math 40S (Pre-Calculus), 2 additional 40S courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming competitions; computer clubs; hackathons; tech projects',
    coopOption: true,
    website: 'https://sci.umanitoba.ca/cs/',
    image: 'https://placehold.co/600x400.png',
    hint: 'computer lab'
  },
  {
    universityName: 'University of Manitoba',
    programName: 'Business',
    province: 'Manitoba',
    faculty: 'Asper School of Business',
    minGradeAverage: '77-81%',
    requiredCourses: 'English 40S, Math 40S (Pre-Calculus), 2 additional 40S courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Leadership roles; business competitions; community involvement; entrepreneurship',
    coopOption: true,
    website: 'https://umanitoba.ca/asper/undergraduate-programs/',
    image: 'https://placehold.co/600x400.png',
    hint: 'business students'
  },
  {
    universityName: 'University of Manitoba',
    programName: 'Health Sciences',
    province: 'Manitoba',
    faculty: 'Faculty of Health Sciences',
    minGradeAverage: '85-89%',
    requiredCourses: 'English 40S, Biology 40S, Chemistry 40S, Math 40S',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: '70% grades + 30% non-academic assessment',
    preferredExtracurriculars: 'Healthcare volunteering; research experience; leadership; community service',
    coopOption: false,
    website: 'https://umanitoba.ca/health-sciences/',
    image: 'https://placehold.co/600x400.png',
    hint: 'health science building'
  },
  {
    universityName: 'University of Saskatchewan',
    programName: 'Engineering',
    province: 'Saskatchewan',
    faculty: 'College of Engineering',
    minGradeAverage: '78-82%',
    requiredCourses: 'English A30, Math B30, Chemistry 30, Physics 30',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; design projects; agriculture/mining industry experience',
    coopOption: true,
    website: 'https://engineering.usask.ca/admissions/',
    image: 'https://placehold.co/600x400.png',
    hint: 'university campus'
  },
  {
    universityName: 'University of Saskatchewan',
    programName: 'Computer Science',
    province: 'Saskatchewan',
    faculty: 'College of Arts and Science',
    minGradeAverage: '76-80%',
    requiredCourses: 'English A30, Math B30, 2 additional 30-level courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming competitions; computer clubs; tech projects; agriculture technology',
    coopOption: true,
    website: 'https://artsandscience.usask.ca/computerscience/',
    image: 'https://placehold.co/600x400.png',
    hint: 'computer lab'
  },
  {
    universityName: 'University of Saskatchewan',
    programName: 'Business',
    province: 'Saskatchewan',
    faculty: 'Edwards School of Business',
    minGradeAverage: '75-79%',
    requiredCourses: 'English A30, Math B30, 2 additional 30-level courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Leadership roles; business competitions; agriculture business experience; community service',
    coopOption: true,
    website: 'https://edwards.usask.ca/programs/undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'business students'
  },
  {
    universityName: 'University of Saskatchewan',
    programName: 'Agriculture',
    province: 'Saskatchewan',
    faculty: 'College of Agriculture and Bioresources',
    minGradeAverage: '74-78%',
    requiredCourses: 'English A30, Math B30, Biology 30, Chemistry 30',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Agricultural experience; 4-H; FFA; environmental clubs; rural community involvement',
    coopOption: true,
    website: 'https://agbio.usask.ca/programs/undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'agriculture field'
  },
  {
    universityName: 'Concordia University',
    programName: 'Computer Science',
    province: 'Quebec',
    faculty: 'Gina Cody School of Engineering and Computer Science',
    minGradeAverage: '82-86%',
    requiredCourses: 'English, Mathematics (Calculus), Chemistry or Physics, one additional academic course',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming competitions; hackathons; computer clubs; bilingual skills valued',
    coopOption: true,
    website: 'https://www.concordia.ca/academics/undergraduate/computer-science.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'city campus'
  },
  {
    universityName: 'Concordia University',
    programName: 'Engineering',
    province: 'Quebec',
    faculty: 'Gina Cody School of Engineering and Computer Science',
    minGradeAverage: '80-84%',
    requiredCourses: 'English, Mathematics (Calculus), Chemistry, Physics',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; design projects; robotics; technical leadership',
    coopOption: true,
    website: 'https://www.concordia.ca/ginacody/programs/undergraduate.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'engineering building'
  },
  {
    universityName: 'Concordia University',
    programName: 'Business',
    province: 'Quebec',
    faculty: 'John Molson School of Business',
    minGradeAverage: '79-83%',
    requiredCourses: 'English, Mathematics, 2 additional academic courses',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Leadership roles; business competitions; bilingual skills; international experience',
    coopOption: true,
    website: 'https://www.concordia.ca/jmsb/programs/undergraduate.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'business building'
  },
  {
    universityName: 'Concordia University',
    programName: 'Psychology',
    province: 'Quebec',
    faculty: 'Faculty of Arts and Science',
    minGradeAverage: '76-80%',
    requiredCourses: 'English, Mathematics, 2 additional academic courses',
    admissionType: 'Competitive',
    earlyApplication: false,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Psychology research; mental health awareness; community service; helping professions experience',
    coopOption: false,
    website: 'https://www.concordia.ca/artsci/psychology/programs/undergraduate.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'psychology lecture'
  },
  {
    universityName: 'University of Victoria',
    programName: 'Computer Science',
    province: 'British Columbia',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '84-88%',
    requiredCourses: 'English 12, Pre-Calculus 12, Chemistry 12 or Physics 12, one additional Grade 12 course',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Academic performance + personal profile',
    preferredExtracurriculars: 'Programming competitions; hackathons; tech projects; computer clubs',
    coopOption: true,
    website: 'https://www.uvic.ca/engineering/computerscience/undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'coastal campus'
  },
  {
    universityName: 'University of Victoria',
    programName: 'Engineering',
    province: 'British Columbia',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '82-86%',
    requiredCourses: 'English 12, Pre-Calculus 12, Chemistry 12, Physics 12',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Academic performance + personal profile',
    preferredExtracurriculars: 'Engineering competitions; design teams; robotics; environmental projects',
    coopOption: true,
    website: 'https://www.uvic.ca/engineering/undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'engineering students'
  },
  {
    universityName: 'University of Victoria',
    programName: 'Business',
    province: 'British Columbia',
    faculty: 'Gustavson School of Business',
    minGradeAverage: '81-85%',
    requiredCourses: 'English 12, Pre-Calculus 12, 2 additional Grade 12 courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Academic performance + personal profile',
    preferredExtracurriculars: 'Leadership experience; business competitions; entrepreneurship; sustainability focus',
    coopOption: true,
    website: 'https://www.uvic.ca/gustavson/undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'business school building'
  },
  {
    universityName: 'University of Victoria',
    programName: 'Psychology',
    province: 'British Columbia',
    faculty: 'Faculty of Social Sciences',
    minGradeAverage: '79-83%',
    requiredCourses: 'English 12, 3 additional Grade 12 courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Academic performance + personal profile',
    preferredExtracurriculars: 'Psychology research; mental health advocacy; community service; helping professions',
    coopOption: false,
    website: 'https://www.uvic.ca/socialsciences/psychology/undergraduate/',
    image: 'https://placehold.co/600x400.png',
    hint: 'psychology class'
  },
  {
    universityName: 'Wilfrid Laurier University',
    programName: 'Business Administration',
    province: 'Ontario',
    faculty: 'Lazaridis School of Business and Economics',
    minGradeAverage: '84-88%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: '70% grades + 30% supplementary application',
    preferredExtracurriculars: 'Leadership roles; business competitions; community service; entrepreneurship',
    coopOption: true,
    website: 'https://www.wlu.ca/programs/business-and-economics/undergraduate/business-administration-bba/index.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'university campus'
  },
  {
    universityName: 'Wilfrid Laurier University',
    programName: 'Computer Science',
    province: 'Ontario',
    faculty: 'Faculty of Science',
    minGradeAverage: '80-84%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming competitions; hackathons; computer clubs; tech volunteering',
    coopOption: true,
    website: 'https://www.wlu.ca/programs/science/undergraduate/computer-science-bsc/index.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'computer lab'
  },
  {
    universityName: 'Wilfrid Laurier University',
    programName: 'Kinesiology',
    province: 'Ontario',
    faculty: 'Faculty of Science',
    minGradeAverage: '78-82%',
    requiredCourses: 'English 4U, Biology 4U, Advanced Functions 4U, Chemistry 4U or Physics 4U, one additional 4U course',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Sports participation; coaching; health-related volunteering; fitness leadership',
    coopOption: false,
    website: 'https://www.wlu.ca/programs/science/undergraduate/kinesiology-bsc/index.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'fitness center'
  },
  {
    universityName: 'Wilfrid Laurier University',
    programName: 'Psychology',
    province: 'Ontario',
    faculty: 'Faculty of Science',
    minGradeAverage: '77-81%',
    requiredCourses: 'English 4U, Advanced Functions 4U, 3 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Psychology research; mental health awareness; community service; helping professions experience',
    coopOption: false,
    website: 'https://www.wlu.ca/programs/science/undergraduate/psychology-ba-bsc/index.html',
    image: 'https://placehold.co/600x400.png',
    hint: 'psychology lecture'
  },
  {
    universityName: 'Brock University',
    programName: 'Business Administration',
    province: 'Ontario',
    faculty: 'Goodman School of Business',
    minGradeAverage: '78-82%',
    requiredCourses: 'English 4U, Advanced Functions 4U, 3 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Leadership roles; business activities; community service; co-op focus',
    coopOption: true,
    website: 'https://brocku.ca/programs/undergraduate/business-administration/',
    image: 'https://placehold.co/600x400.png',
    hint: 'university campus'
  },
  {
    universityName: 'Brock University',
    programName: 'Computer Science',
    province: 'Ontario',
    faculty: 'Faculty of Mathematics and Science',
    minGradeAverage: '76-80%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming projects; computer clubs; hackathons; tech volunteering',
    coopOption: true,
    website: 'https://brocku.ca/programs/undergraduate/computer-science/',
    image: 'https://placehold.co/600x400.png',
    hint: 'computer lab'
  },
  {
    universityName: 'Brock University',
    programName: 'Kinesiology',
    province: 'Ontario',
    faculty: 'Faculty of Applied Health Sciences',
    minGradeAverage: '79-83%',
    requiredCourses: 'English 4U, Biology 4U, Advanced Functions 4U, Chemistry 4U or Physics 4U, one additional 4U course',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Sports participation; coaching; health/fitness activities; research experience',
    coopOption: false,
    website: 'https://brocku.ca/programs/undergraduate/kinesiology/',
    image: 'https://placehold.co/600x400.png',
    hint: 'fitness center'
  },
  {
    universityName: 'Brock University',
    programName: 'Nursing',
    province: 'Ontario',
    faculty: 'Faculty of Applied Health Sciences',
    minGradeAverage: '82-86%',
    requiredCourses: 'English 4U, Biology 4U, Chemistry 4U, Advanced Functions 4U, one additional 4U course',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: '70% grades + 30% supplementary application',
    preferredExtracurriculars: 'Healthcare volunteering; leadership; community service; healthcare experience',
    coopOption: false,
    website: 'https://brocku.ca/programs/undergraduate/nursing/',
    image: 'https://placehold.co/600x400.png',
    hint: 'nursing students'
  },
  {
    universityName: 'University of Windsor',
    programName: 'Engineering',
    province: 'Ontario',
    faculty: 'Faculty of Engineering',
    minGradeAverage: '80-84%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, Chemistry 4U, Physics 4U',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Engineering competitions; design projects; automotive industry experience; technical leadership',
    coopOption: true,
    website: 'https://www.uwindsor.ca/engineering/future-students',
    image: 'https://placehold.co/600x400.png',
    hint: 'university campus'
  },
  {
    universityName: 'University of Windsor',
    programName: 'Computer Science',
    province: 'Ontario',
    faculty: 'Faculty of Science',
    minGradeAverage: '78-82%',
    requiredCourses: 'English 4U, Advanced Functions 4U, Calculus & Vectors 4U, 2 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Programming competitions; computer clubs; tech projects; automotive technology',
    coopOption: true,
    website: 'https://www.uwindsor.ca/science/computerscience/future-students',
    image: 'https://placehold.co/600x400.png',
    hint: 'computer lab'
  },
  {
    universityName: 'University of Windsor',
    programName: 'Business Administration',
    province: 'Ontario',
    faculty: 'Odette School of Business',
    minGradeAverage: '76-80%',
    requiredCourses: 'English 4U, Advanced Functions 4U, 3 additional 4U courses',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: 'Primarily grades-based',
    preferredExtracurriculars: 'Leadership roles; business competitions; automotive business experience; cross-border commerce',
    coopOption: true,
    website: 'https://www.uwindsor.ca/business/programs/undergraduate',
    image: 'https://placehold.co/600x400.png',
    hint: 'business building'
  },
  {
    universityName: 'University of Windsor',
    programName: 'Nursing',
    province: 'Ontario',
    faculty: 'Faculty of Nursing',
    minGradeAverage: '81-85%',
    requiredCourses: 'English 4U, Biology 4U, Chemistry 4U, Advanced Functions 4U, one additional 4U course',
    admissionType: 'Competitive',
    earlyApplication: true,
    evaluationCriteria: '70% grades + 30% CASPer test',
    preferredExtracurriculars: 'Healthcare volunteering; leadership; community service; healthcare experience',
    coopOption: false,
    website: 'https://www.uwindsor.ca/nursing/future-students',
    image: 'https://placehold.co/600x400.png',
    hint: 'nursing students'
  },
];
